apiVersion: "v1"
kind: "Pod"
metadata:
  name: "emptydir"
spec:
  containers:
    -
      name: "main"
      image: "busybox:1.37"
      command:
        - "sh"
        - "-c"
        - "sleep 3600"
      volumeMounts:
        -
          name: "scratch"
          mountPath: "/data"
  restartPolicy: "Never"
  volumes:
    -
      name: "scratch"
      emptyDir: {}
