apiVersion: "v1"
kind: "Pod"
metadata:
  name: "termination"
spec:
  containers:
    -
      name: "main"
      image: "busybox:1.37"
      command:
        - "sh"
        - "-c"
        - "trap 'echo received-TERM; exit 0' TERM; while true; do sleep 1; done"
  restartPolicy: "Never"
  terminationGracePeriodSeconds: 15
